### ISSUE TITLE
Open to expose `normalize-url` arguments?

### ISSUE THREAD

**Issue by mathieumg** [sindresorhus/humanize-url#2]
I was trying to humanize an URL which I already pass through `normalize-url`, but looking at this module's code it passes it to `normalize-url` as well, with default options. The problem is that I'm not using all the same options, so I can't pass the result of my `normalize-url` call back to this module. Is that simply out of the scope of this module, or would it be relevant to add a way to redirect options to the underlying normalize call?

Thank you!

**Comment by sindresorhus** [comment]
I would prefer not exposing the options, but can you elaborate on your use-case? Maybe there's something this module can do better.

**Comment by mathieumg** [comment]
We use the `stripHash: false` option in `normalize-url` options to make the "humanized" links clean yet informative. (We don't want to strip out the hash)

I see a few other ways to solve this:

* Make `stripHash: true` the default in `normalize-url`, because stripping out the hash seems a bit of an agressive default to me.
* Add `stripProtocol` and `stripAuth` options to `normalize-url`, and then this module becomes moot I imagine.

Welcome to other suggestions! Thank you.

**Comment by sindresorhus** [comment]
> Make stripHash: true the default in normalize-url, because stripping out the hash seems a bit of an agressive default to me.

I assume you meant to write `false` not `true` there. I agree though, and I don't remember why I made it `true` by default.

**Comment by sindresorhus** [comment]
Let's do both your suggestions. That way people that just want a good default can use this module (which would be most), but if they need more power, they can use `normalize-url`. PR welcome :)

**Comment by mathieumg** [comment]
> I assume you meant to write `false` not `true` there.

I did, sorry!

Cool, I'll get on it in the next few days when I get a spare second! 🎉 

Thank you.

Should I leave this issue open here since it's going to be a breaking change and will need a bump in both repositories?

**Comment by sindresorhus** [comment]
Yup. Leave it open :)
